server {
    listen 80;
    listen [::]:80;

    server_name example.com www.example.com; # 請將此處替換為你的真實網域
    root /var/www/html; # 請將此處替換為你網頁資料夾或位置
    index index.php index.html index.htm;

    # 無條件導向邏輯
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP 處理區塊
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.4-fpm.sock; # 請依照實際安裝的 PHP 版本調整 sock 檔名
    }

    # 自訂 404 錯誤頁面
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
